
version: 2

sources:
        - name: reddit_comments
          database: fh-bigquery
          tables:
                - name: '20*'
        - name: reddit_posts
          database: fh-bigquery
          tables:
                - name: '20*'

# models:
    # - name: my_first_dbt_model
    #   description: "A starter dbt model"
    #   columns:
    #       - name: id
    #         description: "The primary key for this table"
    #         tests:
    #             - unique
    #             - not_null

    # - name: my_second_dbt_model
    #   description: "A starter dbt model"
    #   columns:
    #       - name: id
    #         description: "The primary key for this table"
    #         tests:
    #             - unique
    #             - not_null
